version: '3.4'

x-base:
  &baseimage
  depends_on:
    - 'redis'
    - 'postgres'
  build: .
  image: local_basename:1.0
  environment:
    REDIS_URL: redis://redis:6379
    DATABASE_URL: postgres://ror:JvHs6MbCGasde2@postgres:5432/ror_db
    DB_HOST: 'postgres'
    DB_NAME: 'ror_db'
    DB_PORT: '5432'
    DB_USER: 'ror'
    DB_PASSWORD: 'JvHs6MbCGasde2'
    PORT: '3000'
    RAILS_ENV: 'development'

services:
  web:
    <<: *baseimage
    command: puma
    expose:
      - '3000'
    ports:
      - '3000:3000'
    depends_on:
      - 'migrations'
    networks:
      - backend
  migrations:
    <<: *baseimage
    command: rake db:migrate
    networks:
      - backend
  crono:
    <<: *baseimage
    command: bundle exec crono
    depends_on:
      - 'migrations'
    networks:
      - backend
  sidekiq:
    <<: *baseimage
    command: sidekiq -c 1
    networks:
      - backend
  redis:
    image: 'redis:latest'
    volumes:
      - 'redis:/data'
    networks:
      - backend
  postgres:
    image: 'postgres:11'
    volumes:
      - 'postgres:/var/lib/postgresql/data'
    environment:
      POSTGRES_DB: 'ror_db'
      POSTGRES_USER: 'ror'
      POSTGRES_PASSWORD: 'JvHs6MbCGasde2'
    networks:
      - backend
volumes:
  redis:
  postgres:
networks:
  backend:
    external: true